services:
  react-app:
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - "3200:3000" 
    environment:
      - NODE_ENV=production 
      - REACT_APP_EMAILJS_SERVICE_ID=${REACT_APP_EMAILJS_SERVICE_ID}
      - REACT_APP_EMAILJS_PUBLIC_KEY=${REACT_APP_EMAILJS_PUBLIC_KEY}
      - REACT_APP_EMAILJS_TEMPLATE_ID=${REACT_APP_EMAILJS_TEMPLATE_ID}