FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve

ARG REACT_APP_EMAILJS_SERVICE_ID
ENV REACT_APP_EMAILJS_SERVICE_ID $REACT_APP_EMAILJS_SERVICE_ID
ARG REACT_APP_EMAILJS_PUBLIC_KEY
ENV REACT_APP_EMAILJS_PUBLIC_KEY $REACT_APP_EMAILJS_PUBLIC_KEY
ARG REACT_APP_EMAILJS_TEMPLATE_ID
ENV REACT_APP_EMAILJS_TEMPLATE_ID $REACT_APP_EMAILJS_TEMPLATE_ID

EXPOSE 3000

CMD [ "npm", "start" ]