services:
  react-app:
    build: 
      context: . 
      dockerfile: Dockerfile
      args:
        REACT_APP_EMAILJS_SERVICE_ID: ${SERVICE_ID}
        REACT_APP_EMAILJS_PUBLIC_KEY: ${PUBLIC_KEY}
        REACT_APP_EMAILJS_TEMPLATE_ID: ${TEMPLATE_ID}
    ports:
      - "3200:3200" 
    environment:
      - NODE_ENV=production
    env_file:
      - .env
